// node test.js — extracts the DOM-free core <script> from viewer.html, runs derive()/normalizeRaw()/splitsOf() and prints the acceptance table.
const fs=require('fs'),path=require('path'),dir=__dirname;
const html=fs.readFileSync(path.join(dir,'viewer.html'),'utf8');
const blocks=html.split('<script>').slice(1).map(s=>s.split('</script>')[0]);
new Function(blocks.join('\n'));                                   // 1. syntax of all JS blocks (concatenated in order)
const C=new Function(blocks[0]+';return {derive,normalizeRaw,splitsOf,capOf,baseOf,baseLane,BENCH,benchVerdicts,LATEST,RUN_IDS,ALL_RUNS,STORY,STAGE,stageOf,directiveOf,solverLabel};')();   // 2. core block alone, no DOM
const inlined=[...html.matchAll(/<script type="application\/json" id="(run-\d+)">/g)].map(m=>m[1]);
const load=k=>JSON.parse(fs.readFileSync(path.join(dir,'traces',k+'.json'),'utf8'));
const files=fs.readdirSync(path.join(dir,'traces')).filter(f=>/^run-\d+\.json$/.test(f)).map(f=>f.slice(0,-5)).sort();
console.log('inline blocks:',inlined.join(', '),'| LATEST =',C.LATEST,'| RUN_IDS =',C.RUN_IDS.join(', '),'| JS lines:',blocks.join('\n').split('\n').length,'| file lines:',html.split('\n').length);
const row=(k,T,D)=>{const b=D.base;
  console.log(`${k}${inlined.includes(k)?' (inline)':''} [${C.stageOf(k,T)||'—'}] | tokens ${D.total.toLocaleString('en-US')} (${D.prompt.toLocaleString('en-US')}+${D.completion.toLocaleString('en-US')}) | ratio ${b?(D.total/b.tok).toFixed(2)+' → '+(D.total/b.tok).toFixed(1)+'×':'—'} | input ${(D.prompt/D.total*100).toFixed(1)}% | calls ${D.calls.length} | tasks ${D.spans.length} (${D.dupCount}) | waves ${D.waves.length} | directive ${D.directive} | dur ${D.dur.toFixed(1)} | plan-ready ${D.plan?D.plan.t:'—'} | first/last call ${D.calls[0].t} / ${D.calls[D.calls.length-1].t}`);
  console.log(`   subtotals ${D.spans.map(s=>`#${s.n} ${s.title}@w${s.wave} ${(s.prompt+s.completion).toLocaleString('en-US')}·${s.calls.length}·${s.dur.toFixed(2)}s${s.dup?' dup':''}${s.wallDur!=null?' (durationSec '+s.wallDur+')':''}`).join(' · ')} | first→last ${JSON.stringify(D.spans.map(s=>[s.first,s.last]))}`);
  console.log(`   gaps ${JSON.stringify(D.gaps.map(g=>[g.t0,g.t1]))} | flags ${D.flags.length}: ${D.flags.map(i=>D.flag[i]+'@#'+(i+1)).join(' ')} | serialClaim ${D.serialClaim?'non-null':'null'} | agents ${T.agents.length} / with calls ${D.active} (+planner) | solvers ${C.solverLabel(D)} | planner ${(D.planner||{}).model} | rejected ${T.meta.rejectedPlansBefore} | events ${T.events.length} | trace.tokens.total ${D.traceTotal===D.total?'✓':'✗'}`);
  if(D.waves.length>1)console.log(`   waves ${JSON.stringify(D.waves.map(w=>({n:w.n,t0:w.t0,t1:w.t1,spans:w.spans,calls:w.calls,tokens:w.tokens,dup:w.dup,agents:w.agents})))} | depWaves ${JSON.stringify(D.depWaves.map(w=>({n:w.n,prev:w.prev,gap:w.gap,ok:w.ok})))} | deps ${JSON.stringify(D.deps.map(d=>({title:d.title,first:d.first,mean:d.mean,inject:d.inject,out:d.out,candidates:d.candidates})))} | firstOnly ${D.firstOnly}`);};
const DD={};for(const k of files){const T=load(k);DD[k]=C.derive(T);row(k,T,DD[k]);}
// checks against the spec's acceptance table + owner's run-004 / run-008 numbers
const assert=(c,m)=>{if(!c){console.error('ASSERT FAILED:',m);process.exitCode=1;}};
assert(C.LATEST==='run-008'&&C.RUN_IDS[0]===C.LATEST&&C.ALL_RUNS.includes('run-009')&&!C.RUN_IDS.includes('run-009x')&&['run-008','run-004','run-001'].every(k=>inlined.includes(k)),'LATEST / inline blocks');
assert(C.stageOf('run-008',load('run-008'))==='앙상블'&&C.stageOf('run-004',load('run-004'))==='절감'&&C.stageOf('run-001',load('run-001'))==='첫 시도'&&C.stageOf('run-009',{meta:{version:'v6.0 DIRECT (최종 제출)'}})==='최종','stageOf (run-009 = 최종 from meta.version)');
const a1=DD['run-001'];assert(a1.total===26808&&a1.calls.length===28&&a1.spans.length===3&&a1.dupCount===2&&+a1.dur.toFixed(1)===60.2&&a1.waves.length===1&&a1.directive===1,'run-001 totals');
assert(JSON.stringify(a1.spans.map(s=>s.prompt+s.completion))==='[10629,4330,11849]','run-001 subtotals');assert(JSON.stringify(a1.spans.map(s=>[s.first,s.last]))==='[[487,1277],[487,758],[522,1196]]','run-001 first/last');
assert(a1.serialClaim!==null&&DD['run-003'].serialClaim===null&&DD['run-004'].serialClaim===null,'serialClaim');assert(a1.flags.length===9&&DD['run-004'].flags.length===2,'flag counts');
if(DD['run-002'])assert(DD['run-002'].total===1564&&DD['run-002'].calls.length===2,'run-002');if(DD['run-003'])assert(DD['run-003'].total===1645&&DD['run-003'].plan.t===12.47,'run-003');
const a4=DD['run-004'];assert(a4.total===1611&&a4.prompt===1501&&a4.completion===110&&a4.calls.length===2&&a4.spans.length===1&&a4.dupCount===0&&a4.plan.t===14.44&&a4.calls[0].t===15.89&&a4.calls[1].t===16.53&&(a4.total/a4.base.tok).toFixed(1)==='2.6'&&a4.directive===1,'run-004');
// run-008 (v7.1 ensemble, local GUI): 5 tasks in 2 waves, SOLVE-A duplicated, JUDGE depends on wave 1 and receives the candidates as extra prompt
const a8=DD['run-008'];assert(a8.total===12544&&a8.prompt===11684&&a8.completion===860&&a8.calls.length===10&&a8.spans.length===5&&a8.dupCount===1&&+a8.dur.toFixed(1)===37.3&&a8.plan.t===22.6&&a8.directive===4&&a8.active===4&&a8.solvers.length===4,'run-008 totals');
assert(a8.waves.length===2&&JSON.stringify(a8.waves[0].spans)==='[1,2,3,4]'&&JSON.stringify(a8.waves[1].spans)==='[5]'&&a8.waves[0].agents.length===3&&a8.waves[0].dup===1&&a8.spans[4].wave===2,'run-008 waves');
assert(a8.depWaves.length===1&&a8.depWaves[0].ok&&a8.depWaves[0].gap===0.3&&a8.deps.length===1&&a8.deps[0].title==='JUDGE'&&a8.deps[0].first===1327&&a8.deps[0].mean===1131&&a8.deps[0].inject===196&&a8.deps[0].out===43&&a8.deps[0].candidates===4,'run-008 dependency + context injection');
assert(a8.flags.map(i=>a8.flag[i]).join(' ')==='gap serial dup wave dep grader done'&&a8.firstOnly===6153&&a8.serialClaim!==null,'run-008 flags (gap serial dup wave dep grader done) + firstOnly');
assert(/입력 \+196 tok/.test(C.capOf(load('run-008'),a8,a8.deps[0].i))&&/웨이브 2가 웨이브 1 완료 후 시작 — 의존성 준수/.test(C.capOf(load('run-008'),a8,a8.depWaves[0].i))&&/플래너의 마지막 말에서만 난다/.test(C.capOf(load('run-008'),a8,a8.agg.i)),'run-008 captions');
// 0-task shape (v6.0 DIRECT, synthetic until run-009 arrives): planner answers directly, one fan-out Solver twin makes a call, no tasks/waves
const T0={meta:{squad:'BIBIMBAP',request:'Answer directly.',durationSec:9.0,version:'v6.0 DIRECT (최종 제출)'},agents:[{id:'p',name:'Conductor',role:'planner',model:'gpt-oss-120b',planner:true},{id:'s',name:'Solver',role:'Solver',model:'gpt-oss-120b',planner:false}],tasks:[],
  events:[{t:0,type:'planning-started',phase:'planning',agentId:'p',agentName:'Conductor',summary:'plan'},{t:1,type:'agent-state-changed',phase:'planning',agentId:'s',agentName:'Solver',detail:{state:'running'},summary:'run'},{t:3,type:'execution-token-usage',phase:'planning',agentId:'s',agentName:'Solver',tokens:{prompt:500,completion:300,cumPrompt:500,cumCompletion:300},summary:'call'},{t:3.1,type:'agent-state-changed',phase:'planning',agentId:'s',agentName:'Solver',detail:{state:'idle'},summary:'idle'},
    {t:8,type:'plan-ready',phase:'planning',agentId:'p',agentName:'Conductor',detail:{taskCount:0,waves:[]},summary:'plan 0'},{t:8,type:'execution-started',phase:'execution',summary:'exec'},{t:8.5,type:'aggregation-started',phase:'aggregation',agentId:'p',agentName:'Conductor',summary:'agg'},{t:9,type:'execution-completed',phase:'aggregation',summary:'done',detail:{result:'42'}}],tokens:{prompt:500,completion:300,total:800},baseline:{item:'x',model:'gpt-oss-120b',correct:true,prompt:131,completion:486,seconds:5.09}};
const D0=C.derive(T0);console.log('0-task (synthetic v6.0 DIRECT):',`tokens ${D0.total} | calls ${D0.calls.length} | tasks ${D0.spans.length} | waves ${D0.waves.length} | deps ${D0.deps.length} | solvers ${C.solverLabel(D0)} | firstOnly ${D0.firstOnly} | flags ${D0.flags.map(i=>D0.flag[i]+'@#'+(i+1)).join(' ')} | stage ${C.stageOf('run-009',T0)} | plan caption: ${C.capOf(T0,D0,4)}`);
assert(D0.total===800&&D0.spans.length===0&&D0.waves.length===0&&D0.deps.length===0&&D0.firstOnly===800&&D0.flags.length===2&&/직접 답했다/.test(C.capOf(T0,D0,4))&&C.stageOf('run-009',T0)==='최종','0-task derive');
const base=C.baseOf(load('run-004'));console.log('baseline lane:',JSON.stringify(C.baseLane(base).label),'| tok',base.tok,'| s',base.s);
console.log('splits v1 → run-003:',JSON.stringify(C.splitsOf(a1,DD['run-003'])));console.log('splits v1 → run-004:',JSON.stringify(C.splitsOf(a1,a4)));console.log('splits 단독 → run-008:',JSON.stringify(C.splitsOf(C.baseLane(base),a8)));
console.log('caption #8 run-001:',C.capOf(load('run-001'),a1,7),'| flag captions run-008:',a8.flags.map(i=>C.capOf(load('run-008'),a8,i)).join(' || '));
// BENCH (owner numbers) + verdict templates
console.log('BENCH:');C.BENCH.tracks.forEach(t=>console.log(`   ${t.name}: base ${t.base?`${t.base.acc}% (n=${t.base.n}) · ${t.base.tok} tok`:'— (not measured)'} → latest ${t.latest.acc}% (n=${t.latest.n}, CI90 ${t.latest.ci.join('–')}%) · ${t.latest.tok.toLocaleString('en-US')} tok${t.ref?' ['+t.ref+']':''}`));
const v=C.benchVerdicts();console.log('   verdict A:',v.A);console.log('   verdict B:',v.B);console.log('   excluded:',C.BENCH.excluded,'| planner:',JSON.stringify(C.BENCH.planner));
console.log('   leaderboard v7.1:',JSON.stringify(C.BENCH.leaderboard.v71),'| final:',C.BENCH.finalSquad.label,'| story:',C.BENCH.story,'| keynote:',C.BENCH.keynote.q);
// 3. normalizeRaw: rebuild an AI:GO events.jsonl (+ .squad.json) from a trace (cumulative counters) and prove drop ingestion yields the same figures
function jsonlOf(T,rejectedBefore){const pl=T.agents.find(a=>a.planner);let wave=0;
  const payload=e=>{const d=e.detail||{};switch(e.type){
    case'planning-started':return{request:T.meta.request};case'plan-ready':return{taskCount:d.taskCount,waves:d.waves,autoApprove:d.autoApprove};
    case'execution-started':return{totalTasks:T.tasks.length,totalWaves:(T.events.find(x=>x.type==='plan-ready').detail.waves||[]).length};case'task-wave-started':return{waveIndex:wave++,taskIds:d.taskIds};
    case'task-status-changed':{const m=/(\w+) → (\w+)/.exec(e.summary);return{taskId:e.taskId,oldStatus:m[1],newStatus:m[2]};}   // no taskTitle in raw status events → title must come from task-completed (fix 2)
    case'agent-state-changed':return{agentId:e.agentId,state:d.state};case'execution-token-usage':return{promptTokens:e.tokens.cumPrompt,completionTokens:e.tokens.cumCompletion};
    case'token-usage-update':return{agentId:e.agentId,promptTokens:d.cumPrompt,completionTokens:d.cumCompletion,total:d.cumPrompt+d.cumCompletion};
    case'task-completed':return{taskId:e.taskId,taskTitle:T.tasks.find(t=>t.id===e.taskId).title,success:d.success,taskCounts:d.taskCounts};
    case'aggregation-started':return{taskIds:T.tasks.map(t=>t.id)};case'execution-completed':return{result:d.result,tokenUsage:{promptTokens:T.tokens.prompt,completionTokens:T.tokens.completion}};}};
  const squad={config:{name:T.meta.squad,plannerAgentId:pl.id,agents:T.agents.map(a=>({id:a.id,name:a.name,role:{value:a.role},modelPreferences:{preferredModelId:'furiosa-ai/'+a.model}}))}};
  const pre=rejectedBefore?[{timestamp:'2026-08-22T04:50:00.000000Z',eventType:'squad:planning-started',payload:{request:'x'}},{timestamp:'2026-08-22T04:50:05.000000Z',eventType:'squad:plan-ready',payload:{taskCount:2,waves:[[]]}}]:[];
  return{jsonl:pre.concat(T.events.map(e=>({timestamp:e.ts,eventType:'squad:'+e.type,payload:payload(e)}))).map(o=>JSON.stringify(o)).join('\n'),squad};}
const T1=load('run-001'),J1=jsonlOf(T1,true),N=C.normalizeRaw(J1.jsonl,J1.squad,load('run-004')),DN=C.derive(N);
console.log('normalizeRaw(events.jsonl from run-001):',`events ${N.events.length} | tokens ${DN.total.toLocaleString('en-US')} (${N.tokens.prompt}+${N.tokens.completion}) | calls ${DN.calls.length} | tasks ${DN.spans.length} (${DN.dupCount}) · insights.duplicateTasks ${N.insights.duplicateTasks} | titles ${[...new Set(DN.spans.map(s=>s.title))].join(',')} | span agents ${[...new Set(DN.spans.map(s=>s.agentName))].join(',')} | first status agentId ${N.events[4].agentName} | rejectedPlansBefore ${N.meta.rejectedPlansBefore} | dur ${N.meta.durationSec} | borrowedBaseline ${N.meta.borrowedBaseline} | subtotals ${JSON.stringify(DN.spans.map(s=>s.prompt+s.completion))} | flags ${DN.flags.length}`);
assert(DN.total===26808&&DN.calls.length===28&&DN.spans.length===3&&DN.dupCount===2&&N.insights.duplicateTasks===2&&DN.spans.every(s=>s.title==='SOLVE')&&N.events[4].agentName==='Math-Solver'&&N.meta.rejectedPlansBefore===1,'normalizeRaw');
const T8=load('run-008'),J8=jsonlOf(T8,false),N8=C.normalizeRaw(J8.jsonl,J8.squad,T8),DN8=C.derive(N8);
console.log('normalizeRaw(events.jsonl from run-008):',`events ${N8.events.length} | tokens ${DN8.total.toLocaleString('en-US')} | calls ${DN8.calls.length} | tasks ${DN8.spans.length} (${DN8.dupCount}) | waves ${DN8.waves.length} ${JSON.stringify(DN8.waves.map(w=>w.spans))} | deps ${JSON.stringify(DN8.deps.map(d=>[d.title,d.inject]))} | flags ${DN8.flags.map(i=>DN8.flag[i]).join(' ')}`);
assert(DN8.total===12544&&DN8.calls.length===10&&DN8.spans.length===5&&DN8.dupCount===1&&DN8.waves.length===2&&DN8.deps.length===1&&DN8.deps[0].inject===196&&DN8.depWaves[0].ok,'normalizeRaw multi-wave (run-008)');
console.log(process.exitCode?'SOME ASSERTS FAILED':'ALL ASSERTS PASSED');
